Repository cloudposse/terraform-provider-awsutils, pull requests merged in 2024-03, with the labels that each got.

#55 Update Scaffolding
  .github/mergify.yml
  README.md
  README.yaml
Labels: do not merge, no-release, auto-update, migration

#56 Auto release fix
  .github/settings.yml
  .github/workflows/auto-release.yml
Labels: no-release, needs-cloudposse

#57 Fix release workflow
  .github/workflows/release.yml
Labels: needs-cloudposse

#58 Install git to fix release workflow
  .github/workflows/release.yml
Labels: needs-cloudposse

#59 Update release workflow to install GPG
  .github/workflows/release.yml
Labels: triage, needs-cloudposse
