Repository cloudposse/terraform-provider-awsutils, pull requests merged in 2025-02, with the labels that each got.

#75 Update names_data.csv
  names/names_data.csv
Labels: minor

#73 🐞 fix(go base sdk): version update
  go.mod
  go.sum
  internal/conns/awsclient_gen.go
  internal/conns/config.go
  internal/conns/config_gen.go
  internal/provider/provider.go
Labels: patch, no-release

#77 Enable runs-on
  .github/runs-on.yml
Labels: needs-cloudposse

#78 Use runs-on
  .github/workflows/tests.yml
Labels: needs-cloudposse

#79 Use large disk size for go releases
  .github/workflows/tests.yml
Labels: needs-cloudposse

#80 Use large runs-on runners
  .github/workflows/tests.yml
Labels: triage, needs-cloudposse

#81 Cut release
  main.go
Labels: triage

#84 Revert "🐞 fix(go base sdk): version update (#73)"
  go.mod
  go.sum
  internal/conns/awsclient_gen.go
  internal/conns/config.go
  internal/conns/config_gen.go
  internal/provider/provider.go
Labels: bugfix, patch
